### ISSUE TITLE
Feature: Submit a Poll Response

### ISSUE THREAD

**Issue by mariam138** [mariam138/love-running#1]
**User Story 1**
In order to **provide my opinion with regards to a certain running topic or event** as a **user**, I can **select and submit an answer from a poll**.

## Acceptance Criteria

- options should be displayed as radio buttons
- The first radio button should be selected by default
- A submit button should be present beneath the options
- Confirmation with the user's name should be shown on screen when an answer is submitted

## Tasks

- [ ] Create options as radio button group
- [ ] Make first radio button selected by default - add required attribute
- [ ] Add submit button at bottom of poll
- [ ] Insert input field to collect user name
- [ ] Test functionality
