### ISSUE TITLE
USER STORY: Make poll hidden after expiry date

### ISSUE THREAD

**Issue by mariam138** [mariam138/love-running#2]
As a **site administrator** I can **add a poll expiry date** so that **poll answers can be collected for a short period of time to help with website maintenance**.

## Acceptance Criteria

- Show end date of poll on website at bottom of poll
- Automatically hide poll from user view after expiry date

## Tasks
- [ ] Create HTML and CSS for poll
- [ ] Detect expiry date of poll (using javascript ?)
- [ ] Make poll hidden from view on expiry date
- [ ] Update website layout to account for hidden poll
- [ ] Test the functionality
