### ISSUE TITLE
USER STORY: Add social media sign up

### ISSUE THREAD

**Issue by mariam138** [mariam138/love-running#3]
In order to **sign up/sign in quickly onto the website** as a **user**, I can **connect my social media log ins for ease and speed**.

## Acceptance Criteria

- Each social media sign up/sign in should be present as a button
- The social media buttons should be present underneath the default sign in section
- When the button is clicked, the user should be directed to the relative social media page, asking permission to connect their account
- Sign ups for Google, Facebook and Twitter/X should be used

## Tasks

- [ ] Create sign up button for Google
- [ ] Create sign up button for Facebook
- [ ] Create sign up button for Twitter/X
- [ ] Open link in new tab when button is clicked
- [ ] Link to user's social media log in
- [ ] Ask user permission to connect their social media account to the website
- [ ] Test functionality
